// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Experiences {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  start_date: string;
  end_date?: string;
  summary?: string;
  link_name?: string;
  link?: string;
  important?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Presentations {
  id: string;
  slug: string | null;
  status: string;
  event_name: string;
  presentation_type: string;
  presentation_date: string;
  presentation_title?: string;
  link?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Works {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  type: string;
  start_date: string;
  end_date?: string;
  summary: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    experiences: Experiences;
    pages: Page;
    presentations: Presentations;
    works: Works;
  }
}