// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock } from "emdash";

export interface Award {
  id: string;
  slug: string | null;
  status: string;
  award: string;
  event_name: string;
  award_date: string;
  summary: string;
  link?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Experiences {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  start_date: string;
  end_date?: string;
  summary?: string;
  link_name?: string;
  link?: string;
  important?: boolean;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image?: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  content?: PortableTextBlock[];
  excerpt?: string;
  published_date?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Presentation {
  id: string;
  slug: string | null;
  status: string;
  event_name: string;
  presentation_type: string;
  presentation_date: string;
  presentation_title?: string;
  link?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

export interface Work {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  type: string;
  start_date: string;
  end_date?: string;
  summary: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
}

declare module "emdash" {
  interface EmDashCollections {
    awards: Award;
    experiences: Experiences;
    pages: Page;
    posts: Post;
    presentations: Presentation;
    works: Work;
  }
}