import { getKeys } from '@/utils';
import {
  Aws,
  AstroIcon,
  Biomejs,
  C,
  CloudflareWorkersIcon,
  Css3Icon,
  DockerIcon,
  DrizzleOrm,
  Electron,
  Eslint,
  FastapiIcon,
  FirebaseIcon,
  Flutter,
  GitIcon,
  GithubIcon,
  GithubActions,
  Hono,
  Html5,
  Javascript,
  KotlinIcon,
  Mysql,
  Numpy,
  Postgresql,
  Nestjs,
  Nextjs,
  PandasIcon,
  Prisma,
  Python,
  Prettier,
  Php,
  RaspberryPi,
  _React,
  Rails,
  Rust,
  Sass,
  SvelteIcon,
  SupabaseIcon,
  Swift,
  Tauri,
  Threejs,
  TypescriptIcon,
  Tailwind,
  Vite,
  Vitest,
  _Vue,
  Jotai,
  StorybookIcon,
  Trpc,
  Ruby,
} from '@dev.icons/react';

export const ICON_MAP = {
  aws: { name: 'AWS', icon: Aws },
  astro: { name: 'Astro', icon: AstroIcon },
  biome: { name: 'Biome', icon: Biomejs },
  c: { name: 'C', icon: C },
  cloudflareWorkers: { name: 'Cloudflare Workers', icon: CloudflareWorkersIcon },
  css: { name: 'CSS', icon: Css3Icon },
  docker: { name: 'Docker', icon: DockerIcon },
  drizzleOrm: { name: 'Drizzle ORM', icon: DrizzleOrm },
  electron: { name: 'Electron', icon: Electron },
  eslint: { name: 'ESLint', icon: Eslint },
  fastapi: { name: 'FastAPI', icon: FastapiIcon },
  firebase: { name: 'Firebase', icon: FirebaseIcon },
  flutter: { name: 'Flutter', icon: Flutter },
  git: { name: 'Git', icon: GitIcon },
  github: { name: 'GitHub', icon: GithubIcon },
  githubActions: { name: 'GitHub Actions', icon: GithubActions },
  hono: { name: 'Hono', icon: Hono },
  html: { name: 'HTML5', icon: Html5 },
  javascript: { name: 'JavaScript', icon: Javascript },
  kotlin: { name: 'Kotlin', icon: KotlinIcon },
  mysql: { name: 'MySQL', icon: Mysql },
  numpy: { name: 'NumPy', icon: Numpy },
  postgresql: { name: 'PostgreSQL', icon: Postgresql },
  nestjs: { name: 'NestJS', icon: Nestjs },
  nextjs: { name: 'Next.js', icon: Nextjs },
  pandas: { name: 'Pandas', icon: PandasIcon },
  prisma: { name: 'Prisma', icon: Prisma },
  python: { name: 'Python', icon: Python },
  prettier: { name: 'Prettier', icon: Prettier },
  php: { name: 'PHP', icon: Php },
  raspberryPi: { name: 'Raspberry Pi', icon: RaspberryPi },
  react: { name: 'React', icon: _React },
  rails: { name: 'Ruby on Rails', icon: Rails },
  rust: { name: 'Rust', icon: Rust },
  scss: { name: 'Sass', icon: Sass },
  storybook: { name: 'Storybook', icon: StorybookIcon },
  svelte: { name: 'Svelte', icon: SvelteIcon },
  supabase: { name: 'Supabase', icon: SupabaseIcon },
  swift: { name: 'Swift', icon: Swift },
  tauri: { name: 'Tauri', icon: Tauri },
  threejs: { name: 'Three.js', icon: Threejs },
  typescript: { name: 'TypeScript', icon: TypescriptIcon },
  tailwind: { name: 'Tailwind CSS', icon: Tailwind },
  vite: { name: 'Vite', icon: Vite },
  vitest: { name: 'Vitest', icon: Vitest },
  vue: { name: 'Vue.js', icon: _Vue },
  jotai: { name: 'Jotai', icon: Jotai },
  trpc: { name: 'tRPC', icon: Trpc },
  ruby: { name: 'Ruby', icon: Ruby },
} as const satisfies Record<string, { name: string; icon: React.ComponentType }>;

export const ICON_KEYS = getKeys(ICON_MAP).sort();

export type IconKey = keyof typeof ICON_MAP;
